# ===============================================
#          ไฟล์ตั้งค่าปลั๊กอิน BsruShop
# ===============================================

# คำนำหน้าข้อความทั้งหมดของปลั๊กอิน (ใช้โค้ดสีได้)
message-prefix: ""

# ส่วนของการตั้งค่าข้อความต่างๆ ที่แสดงผลในเกม
messages:
  # ชื่อของหน้าต่างร้านค้าหลัก
  main-shop-title: "&8ѕʜᴏᴘ"
  # ข้อความเมื่อผู้เล่นคอนโซลพยายามใช้คำสั่ง
  player-only: "&cคำสั่งนี้สามารถใช้ได้โดยผู้เล่นในเกมเท่านั้น"
  # ข้อความเมื่อช่องเก็บของของผู้เล่นเต็ม
  # {amount} คือจำนวนไอเทมที่ไม่สามารถรับได้
  inventory-full: "&cช่องเก็บของของคุณไม่เพียงพอสำหรับไอเทม {amount} ชิ้น!"
  # ข้อความเมื่อผู้เล่นมีเงินไม่พอ
  # {price} คือราคาของไอเทม
  not-enough-money: "&cคุณมีเงินไม่เพียงพอ! คุณต้องการ {price} Coins"
  # ข้อความเมื่อซื้อของสำเร็จ
  # {amount} = จำนวน, {item_name} = ชื่อไอเทม, {price} = ราคา
  purchase-success: "&aซื้อสำเร็จ! คุณได้ซื้อ {item_name} &aจำนวน {amount}x &aในราคา {price} "
  # ข้อความเมื่อรีโหลดปลั๊กอินสำเร็จ
  reload-success: "&aรีโหลดไฟล์ตั้งค่าสำเร็จ!"
  # ข้อความเมื่อไม่มีสิทธิ์ใช้คำสั่ง
  no-permission: "&cคุณไม่มีสิทธิ์ใช้คำสั่งนี้"
  # ข้อความเมื่อเกิดข้อผิดพลาดในการซื้อ (เช่น ไอเทมถูกลบไปแล้ว)
  invalid-item: "&cไม่พบไอเทมที่ต้องการซื้อ กรุณาลองใหม่อีกครั้ง"
  # ข้อความเมื่อใช้คำสั่งผิด
  invalid-command: "&cคำสั่งไม่ถูกต้อง. รูปแบบที่ถูก: /bsrushop <reload|additem|removeitem>"
  # ข้อความเมื่อแอดมินเพิ่มไอเทมเข้าร้านค้าสำเร็จ
  item-added: "&aเพิ่มไอเทม {item_name} &aลงในหมวดหมู่ {category} &aราคา {price} Coins ที่ช่อง {slot} สำเร็จ"
  # รูปแบบคำสั่ง additem ที่ถูกต้อง
  additem-usage: "&cรูปแบบคำสั่ง: /bsrushop additem <หมวดหมู่> <ราคา> <ช่อง>"
  # ข้อความเมื่อแอดมินไม่ได้ถือไอเทมในขณะใช้คำสั่ง /bsrushop additem
  must-hold-item: "&cคุณต้องถือไอเทมไว้ในมือก่อน"
  # ข้อความเมื่อใส่ค่าที่ไม่ใช่ตัวเลข
  # {input} คือค่าที่ผู้เล่นใส่เข้ามา
  invalid-number: "&c'{input}' ไม่ใช่ตัวเลขที่ถูกต้อง"
  # ข้อความเมื่อไม่พบหมวดหมู่ที่ระบุในไฟล์ items.yml
  category-not-found: "&cไม่พบหมวดหมู่ '{category}' ในไฟล์ items.yml"
  # รูปแบบคำสั่ง removeitem ที่ถูกต้อง
  removeitem-usage: "&cรูปแบบคำสั่ง: /bsrushop removeitem <หมวดหมู่> <ช่อง>"
  # ข้อความเมื่อลบไอเทมออกจากร้านค้าสำเร็จ
  item-removed: "&aลบไอเทมจากช่อง {slot} ในหมวดหมู่ {category} สำเร็จแล้ว"
  # ข้อความเมื่อพยายามลบไอเทมจากช่องที่ว่างอยู่แล้ว
  slot-is-empty: "&eไม่มีไอเทมในช่อง {slot} ของหมวดหมู่ {category}"

# การตั้งค่าเสียงเอฟเฟกต์ต่างๆ
sounds:
  # เสียงเมื่อเปิดหมวดหมู่ในร้านค้า
  open-category:
    name: "UI_BUTTON_CLICK" # ชื่อเสียง สามารถหาได้จาก Minecraft Wiki
    volume: 0.8 #ความดัง (0.0 - 1.0)
    pitch: 1 #ระดับเสียง (0.0 - 2.0)
  # เสียงเมื่อกดปุ่มเพิ่ม/ลดจำนวน
  click-quantity:
    name: "UI_BUTTON_CLICK"
    volume: 0.7
    pitch: 1
  # เสียงเมื่อซื้อของสำเร็จ
  purchase-success:
    name: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 0.7
    pitch: 1
  # เสียงเมื่อซื้อของล้มเหลว (เงินไม่พอ / ของเต็ม)
  purchase-fail:
    name: "ENTITY_VILLAGER_NO"
    volume: 0.7
    pitch: 1.0

# การตั้งค่าหน้าต่าง GUI (Graphical User Interface)
gui-settings:
  # หน้าต่างยืนยันการซื้อ
  purchase-window:
    # คำนำหน้าชื่อหน้าต่าง (จะตามด้วยชื่อไอเทม)
    title-prefix: "&8กำลังซื้อ "
    # กำหนดตำแหน่งของแต่ละปุ่ม (Slot 0-26)
    # ใส่ -1 ถ้าไม่ต้องการให้แสดงปุ่มนั้นๆ
    slots:
      item: 13       # ช่องแสดงไอเทมที่จะซื้อ
      confirm: 23    # ปุ่มยืนยัน
      cancel: 21     # ปุ่มยกเลิก
      plus-1: 15     # ปุ่มบวก 1
      plus-10: 16    # ปุ่มบวก 10
      plus-64: 17    # ปุ่มบวก 64
      minus-1: 11    # ปุ่มลบ 1
      minus-10: 10   # ปุ่มลบ 10
      minus-64: 9    # ปุ่มลบ 64
    # ข้อความบนปุ่มต่างๆ
    buttons:
      plus-1: "&a+1"
      plus-10: "&a+10"
      plus-16: "&a+16 &7(สูงสุด)"
      plus-64: "&a+64 (สูงสุด)"
      minus-1: "&c-1"
      minus-10: "&c-10"
      minus-16: "&c-16 &7(ต่ำสุด)"
      minus-64: "&c-64 (ต่ำสุด)"
      confirm: "&a&lยืนยันการซื้อ"
      cancel: "&c&lยกเลิก"
      # คำอธิบาย (Lore) ที่จะแสดงบนไอเทมในหน้าต่างยืนยันการซื้อ
      # {amount} = จำนวน, {price} = ราคารวม
      item-lore:
        - "&eจำนวน: &f{amount}"
        - "&eราคารวม: &f${price}"
        - "" # บรรทัดว่าง

# รูปแบบของไอเทมที่แสดงในร้านค้า
item-format:
  # คำอธิบาย (Lore) ที่จะถูกเพิ่มเข้าไปใต้ไอเทมทุกชิ้นในร้านค้า
  lore:
    # {price} คือราคาต่อชิ้น
    - "&eราคา: &f${price} "
    - "" # เพิ่มบรรทัดว่าง
    - "&aคลิกเพื่อซื้อ!"